# Generated by Django 5.2.5 on 2025-08-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resourcelink',
            name='category',
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='tags',
            field=models.ManyToManyField(blank=True, to='resources.tag'),
        ),
    ]
