# Generated by Django 5.2.5 on 2025-08-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_tag_remove_resourcelink_category_resourcelink_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelink',
            name='file',
            field=models.FileField(blank=True, help_text='Use this for a File Upload.', upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='link_type',
            field=models.CharField(choices=[('EXTERNAL', 'External URL'), ('UPLOAD', 'File Upload')], default='EXTERNAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='resourcelink',
            name='url',
            field=models.URLField(blank=True, help_text='Use this for an External URL.', max_length=500),
        ),
    ]
