# Generated by Django 5.2.5 on 2025-08-31 14:13

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_productcategory_resourcelink_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcelink',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
