# Generated by Django 5.2.5 on 2025-09-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resourcelink_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='ResourceSetMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('resource_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourcelink')),
                ('resource_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resourceset')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('resource_set', 'resource_link')},
            },
        ),
        migrations.AddField(
            model_name='resourcelink',
            name='sets',
            field=models.ManyToManyField(through='resources.ResourceSetMembership', to='resources.resourceset'),
        ),
    ]
